### ISSUE TITLE
brunch build vs watch

### ISSUE THREAD

**Issue by jahbini** [moonwave99/waffel#3]
The waffle html pipelines only seem active with `brunch watch --server` -- that is, `brunch build` does not generate any html files in the `public` directory.

Or is this only on my 'puter?

**Comment by moonwave99** [comment]
Hi @jahbini , may I have a look at your configuration (i.e. `brunch-config.coffee`)?
Be sure to have latest brunch version (2.x), I just updated to that.

Thank you so much!

**Comment by moonwave99** [comment]
I close this as I got no feedback so far, feel free to report anything else in the future!
