### ISSUE TITLE
Generate slow

### ISSUE THREAD

**Issue by cafe4it** [moonwave99/waffel#7]
Sorry, I do not know English [gg translate]

Generate slow

I have about 2000 files .md takes about 10 minutes to generate.

Ubuntu 14.04
Nodejs: v6.2.1

Thanks.

**Comment by moonwave99** [comment]
Hey @cafe4it, it should definitely be faster than that!

Hard to see where the problem is, without more context. Please post your configuration!

**Comment by cafe4it** [comment]
Thanks. I fixed.
